#!/bin/env perl
use strict;
use warnings;
use 5.010;

my $arg = shift // usage();

system("~/bashpack/scripts/view_command_file more $arg");


sub usage {

    say qq{usage
            $0 SHELL_COMMAND

            This pages either the command itself or ~/.bashrc* if the command cannot be found or if it is an alias.};
    exit();
}
